import React, { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'en' | 'th';

// Define the shape of our translations
// Extending index signature to allow string keys
type Translations = {
    [key: string]: string;
}

const translations: Record<Language, Translations> = {
    en: {
        home: 'Home',
        catalog: 'Catalog',
        preorder: 'Pre-Order',
        updates: 'Updates',
        about: 'About Us',
        orders: 'Orders',
        login: 'Login',
        logout: 'Logout',
        // Call Center
        welcome: 'Welcome to',
        description: 'Your ultimate gateway to the fandom universe.',
        explore: 'Explore Now',
        points: 'pts',
        call_center: 'Call Center',
        help_center: 'Help center',
        help_center_desc: 'We are here to help you 24/7',
        my_tickets: 'My Tickets',
        new_ticket: 'New Ticket',
        faq: 'FAQ',
        create_new_ticket: 'Create New Ticket',
        ticket_subject: 'Subject',
        ticket_category_field: 'Category',
        ticket_priority_field: 'Priority',
        ticket_message_field: 'Message',
        submit_ticket: 'Submit Ticket',
        ticket_messages: 'messages',
        created: 'Created',
        last_updated: 'Last Updated',
        frequently_asked_questions: 'Frequently Asked Questions',
        still_need_help: 'Still need help?',
        contact_support_desc: 'Our support team is ready to assist you',
        create_ticket: 'Create Ticket',
        live_chat: 'Live Chat',
        call_us: 'Call Us',
        // Staff Dashboard
        staff_dashboard: 'Staff Dashboard',
        staff_dashboard_desc: 'Manage customer support and staff members',
        chat_rooms: 'Chat Rooms',
        staff_members: 'Staff Members',
        add_staff: 'Add Staff',
        add_staff_member: 'Add Staff Member',
        active_chats: 'Active Chats',
        chatting_with: 'Chatting with',
        waiting_for_staff: 'Waiting for staff',
        no_staff_assigned: 'No staff assigned',
        select_chat: 'Select a chat room',
        select_chat_desc: 'Choose a chat room to start helping customers',
        type_message: 'Type your message...',
        send: 'Send',
        end_chat: 'End Chat',
        online: 'Online',
        connecting: 'Connecting',
        finding_available_staff: 'Finding available staff...',
        connecting_to_staff: 'Connecting to staff...',
        live_chat_support: 'Live Chat Support',
        you: 'You',
        chat_ended: 'Chat has ended',
        back_to_help_center: 'Back to Help Center',
        welcome_message: 'Hello! How can I help you today?',
        staff_typing_response: 'I understand. Let me help you with that.',
        please_login: 'Please login to access this feature',
        go_to_login: 'Go to Login',
        // Status
        status_open: 'Open',
        status_in_progress: 'In Progress',
        status_resolved: 'Resolved',
        status_closed: 'Closed',
        status_active: 'Active',
        status_waiting: 'Waiting',
        // Priority
        priority_low: 'Low',
        priority_medium: 'Medium',
        priority_high: 'High',
        priority_urgent: 'Urgent',
        // Categories
        category_general: 'General',
        category_shipping: 'Shipping',
        category_payment: 'Payment',
        category_product: 'Product',
        category_account: 'Account',
        category_technical: 'Technical',
        // Staff
        support_staff: 'Support Staff',
        admin: 'Administrator',
        last_seen: 'Last Seen',
        full_name: 'Full Name',
        role: 'Role',
        // Access
        access_denied: 'Access Denied',
        admin_only: 'This page is for administrators only',
        // About Us Page specific
        about_title: 'About DomPort',
        about_desc: 'One-stop service for art toy lovers.',
        contact: 'Contact Us',
        location: 'Location',
        // Orders Page specific
        order_id: 'Order ID',
        date: 'Date',
        status: 'Status',
        total: 'Total',
        items: 'Items',
        // Profile/Settings
        profile: 'Profile',
        settings: 'Settings',
        theme: 'Theme',
        dark_mode: 'Dark Mode',
        light_mode: 'Light Mode',
        language: 'Language',
        your_cart: 'Your Cart',
        cart_empty: 'Your cart is empty',
        // Features
        what_we_offer: 'What We Offer',
        feature_merch_title: 'Official Merchandise',
        feature_merch_desc: '100% Authentic products directly from the studio',
        feature_loyalty_title: 'Loyalty Points',
        feature_loyalty_desc: 'Earn points with every purchase, redeem for instant discounts',
        feature_preorder_title: 'Pre-order System',
        feature_preorder_desc: 'Pre-order items, guaranteed delivery',

        // Footer
        shop: 'Shop',
        who_we_are: 'Who is DomPort?',
        support: 'Support',
        all_products: 'All Products',
        vinyl_figures: 'Vinyl Figures',
        for_fandoms: 'For Fandoms',
        track_order: 'Track Your Order',

        // Login/Register
        welcome_back: 'Welcome Back',
        sign_in_desc: 'Sign in to manage your collection',
        username: 'Username',
        password: 'Password',
        email: 'Email',
        confirm_password: 'Confirm Password',
        remember_me: 'Remember Me',
        sign_in: 'Sign In',
        signing_in: 'Signing In...',
        dont_have_account: "Don't have an account?",
        sign_up: 'Sign Up',
        create_account: 'Create Account',
        join_us: 'Join DomPort today',
        creating_account: 'Creating Account...',
        already_have_account: 'Already have an account?',
        login_here: 'Login here',

        // Statuses
        status_delivered: 'Delivered',
        status_shipped: 'Shipped',
        status_pending: 'Pending',
        status_cancelled: 'Cancelled',

        // Profile specific
        order_history: 'Order History & Tracking',

        // PreOrder
        exclusive_preorders: 'Exclusive Pre-Orders',
        preorder_subtitle: 'Secure the most anticipated items before anyone else.',
        release_date: 'Release',
        total_price: 'Total Price',
        deposit: 'Deposit',
        preorder_now: 'Pre-order Now',

        // Catalog
        explore_fandoms: 'Explore Fandoms',
        catalog_subtitle: 'Search items by your favorite series.',
        search_placeholder: 'Search items...',
        max_price: 'Max Price',
        no_items_found: 'No items found matching your criteria.',
        reset_filters: 'Reset Filters',
        view_details: 'View',
        // Additional keys for Fandom pages
        the_latest_drops: 'The Latest Drops',
        fandom_description: 'Exclusive limited-time campaigns from your favorite fandoms. Get them before they\'re gone!',
        search_fandom: 'Search for your favorite fandom...',
        all_fandoms: 'All Fandoms',
        view_all_fandoms: 'View All Fandom →',
        categories: 'Categories',
        view_all_categories: 'View All Categories →',
        pre_order: 'Pre Order',
        preorder_items_custom_requests: 'Pre-Order Items & Custom Requests',
        cant_find_it: "Can't find it?",
        request_custom_order_provided: 'Request a custom order provided by us.',
        order_custom_product: 'Order Custom Product',
        // Request Custom Product keys
        back_to_preorder: 'Back to Pre-Order',
        send_us_link_order: 'Send us a link, and we\'ll order it for you!',
        select_region_rate: 'Select Region / Rate',
        product_name: 'Product Name',
        product_link_url: 'Product Link (URL)',
        details_size_color: 'Details (Size, Color, etc.)',
        price_foreign_currency: 'Price (in Foreign Currency)',
        estimated_total: 'Estimated Total',
        includes_estimated_shipping: 'Includes estimated shipping to Thailand. Final price may vary.',
        submit_request: 'Submit Request',
        custom_product_request_submitted: 'Custom product request submitted successfully!',
        funded: 'Funded',
        success: 'Success',
        no_fandoms_found: 'No fandoms found matching',
        fandom_not_found: 'Fandom not found',
        no_cover_image: 'No Cover Image',
        products_available: 'Products Available',
        no_products_fandom: 'No products found for this fandom.',
        // Additional keys for CallCenter
        no_tickets_found: 'No tickets found',
        ticket_subject_placeholder: 'Enter ticket subject',
        ticket_message_placeholder: 'Describe your issue in detail...',
        product: 'Product',
        account: 'Account',
        urgent: 'Urgent',
        // Order Tracking keys
        start_production: 'Start Production',
        production_completed: 'Production Completed',
        shipping_to_thailand: 'Shipping to Thailand',
        arrived_in_thailand: 'Arrived in Thailand',
        start_domestic_shipping: 'Start Domestic Shipping',
        // User Management keys
        user_management: 'User Management',
        active_users: 'Active Users',
        blacklisted_users: 'Blacklisted Users',
        recent_deletions: 'Recent Deletions',
        account_info: 'Account Info',
        contact_address: 'Contact & Address',
        ticket_management: 'Ticket Management',
        ticket_details: 'Ticket Details',
        user_details: 'User Details',
        fix_duplicates: 'Fix Duplicates',
        no_active_users_found: 'No active users found',
        no_blacklisted_users: 'No blacklisted users',
        recycle_bin_empty: 'Recycle bin is empty',
        // FAQ keys
        faq_track_order_question: 'How do I track my order?',
        faq_track_order_answer: 'You can track your order by going to your profile and clicking on the order you want to track.',
        faq_return_policy_question: 'What is your return policy?',
        faq_return_policy_answer: 'We offer 30-day return policy for unused items in original packaging.',
        faq_preorder_question: 'How do pre-orders work?',
        faq_preorder_answer: 'Pre-orders allow you to reserve items before they are released. You will be charged a deposit and the remaining amount upon shipping.',
        faq_contact_support_question: 'How do I contact customer support?',
        faq_contact_support_answer: 'You can reach our customer support through the live chat feature or by creating a support ticket.',
        // FandomList keys
        back_to_profile: 'Back to Profile',
        manage_fandoms: 'Manage Fandoms',
        add_new_fandom: 'Add New Fandom',
        enter_fandom_name: 'Enter fandom name...',
        add: 'Add',
        available_fandoms: 'Available Fandoms',
        edit: 'Edit',
        // ProductDetail keys
        today: 'Today',
        tomorrow: 'Tomorrow',
        in_days: 'In',
        in_months: 'In',
        coming_soon: 'Coming soon',
        loading_product_details: 'Loading product details...',
        back_to_catalog: 'Back to Catalog',
        view: 'View',
        preorder_exclusive: 'PRE-ORDER EXCLUSIVE',
        limited_edition: 'LIMITED EDITION',
        in_stock_ready_ship: 'IN STOCK - READY TO SHIP',
        immediate_delivery: 'IMMEDIATE DELIVERY',
        preorder_price: 'PRE-ORDER PRICE',
        now: 'now',
        on_release: 'on release',
        regular_price: 'REGULAR PRICE',
        ships_within_days: 'Ships within 2-3 business days',
        quantity: 'Quantity',
        max_units: 'Max',
        units: 'units',
        out_of_stock: 'Out of Stock',
        product_details: 'Product Details',
        stock: 'Stock',
        product_id_label: 'Product ID',
        material_specifications: 'Material & Specifications',
        material: 'Material',
        premium_pvc_vinyl: 'Premium PVC Vinyl',
        height: 'Height',
        weight: 'Weight',
        base: 'Base',
        paint: 'Paint',
        hand_painted_details: 'Hand-painted details',
        packaging: 'Packaging',
        collectors_box: 'Collector\'s box',
        authenticity: 'Authenticity',
        certificate_included: 'Certificate included',
        limited_edition_pieces: '500 pieces worldwide',
        // Profile keys
        profile_updated_successfully: 'Profile updated successfully!',
        failed_to_update_profile: 'Failed to update profile',
        session_expired_login_again: 'Session expired. Please log in again.',
        error_updating_profile: 'An error occurred while updating profile',
        passwords_do_not_match: 'Passwords do not match',
        cancel: 'Cancel',
        edit_profile: 'Edit Profile',
        change_password: 'Change Password',
        username_label: 'Username',
        full_name_label: 'Full Name',
        phone_label: 'Phone',
        social_media: 'Social Media',
        facebook_url: 'Facebook URL',
        facebook_url_placeholder: 'https://facebook.com/...',
        facebook_name_placeholder: 'Facebook Name',
        twitter_url: 'Twitter URL',
        twitter_url_placeholder: 'https://twitter.com/...',
        twitter_name_placeholder: 'Twitter Name',
        line_id_url: 'Line ID/URL',
        line_id_placeholder: 'Line ID',
        line_name_placeholder: 'Line Name',
        address: 'Address',
        loading_address_data: 'Loading address data...',
        house_number: 'House Number',
        house_number_placeholder: '123/45 Village No.1',
        province: 'Province',
        select_province: 'Select Province',
        district: 'District',
        select_district: 'Select District',
        sub_district: 'Sub-district',
        select_sub_district: 'Select Sub-district',
        postal_code: 'Postal Code',
        auto_filled: 'Auto-filled',
        saving: 'Saving...',
        save_changes: 'Save Changes',
        new_password: 'New Password',
        new_password_placeholder: 'New password',
        confirm_password_label: 'Confirm Password',
        confirm_new_password_placeholder: 'Confirm new password',
        update_password: 'Update Password',
        shipping_address: 'Shipping Address',
        no_orders_found: 'No orders found.',
        order: 'Order',
        my_favorites: 'My Favorites',
        liked_products: 'Liked Products',
        liked_fandoms: 'Liked Fandoms',
        no_favorite_products: 'No favorite products yet.',
        unlike: 'Unlike',
        no_favorite_fandoms: 'No favorite fandoms yet.',
        delete_account: 'Delete Account',
        delete_account_confirm_message: 'Are you sure you want to delete your account? This action cannot be undone and you will lose all your data.',
        delete: 'Delete',
        // Updates additional keys
        by: 'by',
        grand_opening_title: 'Grand Opening of DomPort Online Store!',
        grand_opening_content: 'We are thrilled to announce the official launch of DomPort! Your one-stop shop for all things anime figures and collectibles. To celebrate, we are giving away double points on all first purchases this week!',
        wonder_festival_title: 'Wonder Festival 2024 Recap',
        wonder_festival_content: 'The Winter Wonder Festival was a blast! We saw upcoming prototypes for Chainsaw Man and Spy x Family figures. Check out our gallery for exclusive photos from the event floor.',
        production_delay_title: 'Production Delay: EVA Unit-01',
        production_delay_content: 'We regret to inform you that the release of the EVA Unit-01 Awakening statue has been pushed back by 2 months due to manufacturing adjustments to ensure the highest quality. We apologize for the inconvenience.',
        new_preorders_title: 'New Pre-Orders: Hololive Generation 3',
        new_preorders_content: 'Pre-orders are now open for the entire Hololive Fantasy generation! secure your favorite vtuber scale figure today. Limited stocks available.',
        // Updates additional features keys
        maintenance: 'Maintenance',
        product_launch: 'Launch',
        system_update: 'Update',
        search_updates_placeholder: 'Search updates...',
        sort_by: 'Sort by',
        sort_by_date: 'Date',
        sort_by_category: 'Category',
        reading_time: 'Reading time',
        minutes: 'minutes',
        update_statistics: 'Update Statistics',
        total_updates: 'Total Updates',
        announcements: 'Announcements',
        events: 'Events',
        // Updates page missing keys
        news_updates: 'News & Updates',
        updates_description: 'Stay updated with the latest news, announcements, and events from DomPort.',
        all: 'All',
        announcement: 'Announcement',
        new_release: 'New Release',
        event: 'Event',
        delay: 'Delay',
        no_updates_category: 'No updates found in this category.'
    },
    th: {
        home: 'หน้าหลัก',
        catalog: 'แคตตาล็อก',
        preorder: 'สั่งจองล่วงหน้า',
        updates: 'อัปเดต',
        about: 'เกี่ยวกับเรา',
        orders: 'รายการคำสั่งซื้อ',
        login: 'เข้าสู่ระบบ',
        logout: 'ออกจากระบบ',
        welcome: 'ยินดีต้อนรับสู่',
        description: 'ประตูสู่จักรวาลแฟนดอมที่ดีที่สุดของคุณ',
        explore: 'สำรวจเลย',
        points: 'แต้ม',
        // About Us Page specific
        about_title: 'เกี่ยวกับ DomPort',
        about_desc: 'บริการครบวงจรสำหรับคนรักอาร์ตทอย',
        contact: 'ติดต่อเรา',
        location: 'สถานที่ตั้ง',
        // Orders Page specific
        order_id: 'รหัสคำสั่งซื้อ',
        date: 'วันที่',
        status: 'สถานะ',
        total: 'ยอดรวม',
        items: 'รายการสินค้า',
        // Profile/Settings
        profile: 'โปรไฟล์',
        settings: 'การตั้งค่า',
        theme: 'ธีม',
        dark_mode: 'โหมดมืด',
        light_mode: 'โหมดสว่าง',
        language: 'ภาษา',
        your_cart: 'ตะกร้าของคุณ',
        cart_empty: 'ตะกร้าของคุณว่างเปล่า',
        // Features
        what_we_offer: 'สิ่งที่เรามอบให้',
        feature_merch_title: 'สินค้าลิขสิทธิ์แท้',
        feature_merch_desc: 'สินค้าลิขสิทธิ์แท้ 100% จากค่ายโดยตรง',
        feature_loyalty_title: 'ระบบสะสมแต้ม',
        feature_loyalty_desc: 'ทุกยอดซื้อสะสมแต้ม แลกส่วนลดได้ทันที',
        feature_preorder_title: 'ระบบสั่งจองล่วงหน้า',
        feature_preorder_desc: 'จองสินค้าล่วงหน้า การันตีได้รับของแน่นอน',
        // Call Center additional keys
        order_not_received: 'ไม่ได้รับสินค้า',
        payment_issue: 'ปัญหาการชำระเงิน',
        shipping: 'การจัดส่ง',
        payment: 'การชำระเงิน',
        general: 'ทั่วไป',
        please_fill_required_fields: 'กรุณากรอกข้อมูลให้ครบถ้วน',
        ticket_created_successfully: 'สร้างตั๋วสำเร็จแล้ว!',
        // Status and priority
        open: 'เปิด',
        in_progress: 'กำลังดำเนินการ',
        resolved: 'แก้ไขแล้ว',
        closed: 'ปิด',
        low: 'ต่ำ',
        high: 'สูง',
        // FAQ keys
        frequently_asked_questions: 'คำถามที่พบบ่อย',
        still_need_help: 'ยังต้องการความช่วยเหลือ?',
        contact_support_desc: 'ทีมสนับสนุนของเราพร้อมช่วยเหลือคุณ',
        create_ticket: 'สร้างตั๋ว',
        live_chat: 'แชทสด',
        call_us: 'โทรหาเรา',
        // Staff Dashboard
        staff_dashboard: 'แผงควบคุม',
        staff_dashboard_desc: 'จัดการการสนับสนุนลูกค้าและพนักงาน',
        chat_rooms: 'ห้องแชท',
        staff_members: 'พนักงาน',
        add_staff: 'เพิ่มพนักงาน',
        add_staff_member: 'เพิ่มพนักงาน',
        active_chats: 'แชทที่ใช้งาน',
        chatting_with: 'กำลังคุยกับ',
        waiting_for_staff: 'รอพนักงาน',
        no_staff_assigned: 'ไม่มีพนักงานที่ได้รับมอบหมาย',
        select_chat: 'เลือกห้องแชท',
        select_chat_desc: 'เลือกห้องแชทเพื่อเริ่มช่วยเหลือลูกค้า',
        type_message: 'พิมพ์ข้อความ...',
        send: 'ส่ง',
        end_chat: 'จบการสนทนา',
        online: 'ออนไลน์',
        connecting: 'กำลังเชื่อมต่อ',
        finding_available_staff: 'กำลังหาพนักงานที่ว่าง...',
        connecting_to_staff: 'กำลังเชื่อมต่อกับพนักงาน...',
        live_chat_support: 'สนับสนุนแชทสด',
        you: 'คุณ',
        chat_ended: 'สนทนาสิ้นสุด',
        back_to_help_center: 'ศูนย์ความช่วยเหลือ',
        help_center_desc: 'เราพร้อมช่วยเหลือคุณ 24 ชั่วโมง',
        welcome_message: 'สวัสดี! ฉันจะช่วยเหลือคุณอย่างไรในวันนี้?',
        staff_typing_response: 'เข้าใจครับ ฉันจะช่วยเหลือคุณเรื่องนี้',
        please_login: 'กรุณาเข้าสู่ระบบเพื่อเข้าถึงฟีเจอร์นี้',
        go_to_login: 'ไปที่หน้าเข้าสู่ระบบ',
        close: 'ปิด',
        // Additional keys for Fandom pages
        the_latest_drops: 'มาใหม่ล่าสุด',
        fandom_description: 'แคมเปญจำกัดเวลาพิเศษจากแฟนดอมที่คุณชื่นชอบ จองก่อนหมด!',
        search_fandom: 'ค้นหาแฟนดอมที่คุณชื่นชอบ...',
        all_fandoms: 'ทุกแฟนดอม',
        view_all_fandoms: 'ดูทุกแฟนดอม →',
        categories: 'หมวดหมู่',
        view_all_categories: 'ดูหมวดหมู่ทั้งหมด →',
        pre_order: 'สั่งจองล่วงหน้า',
        preorder_items_custom_requests: 'สินค้าสั่งจองล่วงหน้าและคำขอแบบกำหนดเอง',
        cant_find_it: 'หาไม่เจอ?',
        request_custom_order_provided: 'ขอสินค้าแบบกำหนดเองจากเรา',
        order_custom_product: 'สั่งซื้อสินค้าแบบกำหนดเอง',
        // Request Custom Product keys
        back_to_preorder: 'กลับไปหน้าสั่งจองล่วงหน้า',
        send_us_link_order: 'ส่งลิงก์ให้เรา เราจะสั่งซื้อให้!',
        select_region_rate: 'เลือกประเทศ / อัตรา',
        product_name: 'ชื่อสินค้า',
        product_link_url: 'ลิงก์สินค้า (URL)',
        details_size_color: 'รายละเอียด (ขนาด, สี, อื่นๆ)',
        price_foreign_currency: 'ราคา (ในสกุลเงินต่างประเทศ)',
        estimated_total: 'ราคาโดยประมาณ',
        includes_estimated_shipping: 'รวมค่าจัดส่งโดยประมาณถึงประเทศไทย ราคาสุดท้ายอาจเปลี่ยนแปลง',
        submit_request: 'ส่งคำขอ',
        custom_product_request_submitted: 'ส่งคำขอสินค้าแบบกำหนดเองเรียบร้อย!',
        funded: 'ระดมทุนแล้ว',
        success: 'สำเร็จ',
        no_fandoms_found: 'ไม่พบแฟนดอมที่ตรงกับ',
        fandom_not_found: 'ไม่พบแฟนดอม',
        no_cover_image: 'ไม่มีรูปภาพปก',
        products_available: 'สินค้าที่มีให้',
        no_products_fandom: 'ไม่พบสินค้าสำหรับแฟนดอมนี้',
        // Additional keys for CallCenter
        no_tickets_found: 'ไม่พบตั๋ว',
        create_new_ticket: 'สร้างตั๋วใหม่',
        ticket_subject: 'หัวข้อตั๋ว',
        ticket_category_field: 'หมวดหมู่',
        ticket_priority_field: 'ความสำคัญ',
        ticket_message_field: 'ข้อความ',
        submit_ticket: 'ส่งตั๋ว',
        ticket_subject_placeholder: 'กรอกหัวข้อตั๋ว',
        ticket_message_placeholder: 'อธิบายปัญหาของคุณอย่างละเอียด...',
        product: 'สินค้า',
        account: 'บัญชี',
        urgent: 'เร่งด่วน',
        // Order Tracking keys
        start_production: 'เริ่มการผลิต',
        production_completed: 'การผลิตเสร็จสิ้น',
        shipping_to_thailand: 'จัดส่งไปประเทศไทย',
        arrived_in_thailand: 'ถึงประเทศไทย',
        start_domestic_shipping: 'เริ่มจัดส่งในประเทศ',
        // User Management keys
        user_management: 'จัดการผู้ใช้',
        active_users: 'ผู้ใช้ที่ใช้งาน',
        blacklisted_users: 'ผู้ใช้ที่ถูกบล็อก',
        recent_deletions: 'การลบล่าสุด',
        account_info: 'ข้อมูลบัญชี',
        contact_address: 'ข้อมูลติดต่อและที่อยู่',
        ticket_management: 'จัดการตั๋ว',
        ticket_details: 'รายละเอียดตั๋ว',
        user_details: 'รายละเอียดผู้ใช้',
        fix_duplicates: 'แก้ไขข้อมูลซ้ำ',
        no_active_users_found: 'ไม่พบผู้ใช้ที่ใช้งาน',
        no_blacklisted_users: 'ไม่พบผู้ใช้ที่ถูกบล็อก',
        recycle_bin_empty: 'ถังขยะว่างเปล่า',
        // FAQ keys
        faq_track_order_question: 'ฉันจะติดตามคำสั่งซื้อได้อย่างไร?',
        faq_track_order_answer: 'คุณสามารถติดตามคำสั่งซื้อได้โดยไปที่โปรไฟล์และคลิกที่คำสั่งซื้อที่คุณต้องการติดตาม',
        faq_return_policy_question: 'นโยบายการคืนสินค้าของคุณคืออะไร?',
        faq_return_policy_answer: 'เรามีนโยบายการคืนสินค้า 30 วันสำหรับสินค้าที่ไม่ได้ใช้ในบรรจุภัณฑ์เดิม',
        faq_preorder_question: 'การสั่งจองล่วงหน้าทำงานอย่างไร?',
        faq_preorder_answer: 'การสั่งจองล่วงหน้าช่วยให้คุณจองสินค้าก่อนวางจำหน่าย คุณจะถูกคิดเงินมัดจำและยอดที่เหลือเมื่อจัดส่ง',
        faq_contact_support_question: 'ฉันจะติดต่อฝ่ายสนับสนุนลูกค้าได้อย่างไร?',
        faq_contact_support_answer: 'คุณสามารถติดต่อฝ่ายสนับสนุนลูกค้าของเราผ่านฟีเจอร์แชทสดหรือสร้างตั๋วสนับสนุน',
        // FandomList keys
        back_to_profile: 'กลับไปที่โปรไฟล์',
        manage_fandoms: 'จัดการแฟนดอม',
        add_new_fandom: 'เพิ่มแฟนดอมใหม่',
        enter_fandom_name: 'กรอกชื่อแฟนดอม...',
        add: 'เพิ่ม',
        available_fandoms: 'แฟนดอมที่มีให้',
        edit: 'แก้ไข',
        // ProductDetail keys
        today: 'วันนี้',
        tomorrow: 'พรุ่งนี้',
        in_days: 'ในอีก',
        in_months: 'ในอีก',
        coming_soon: 'เร็วๆ นี้',
        loading_product_details: 'กำลังโหลดรายละเอียดสินค้า...',
        back_to_catalog: 'กลับไปที่แคตตาล็อก',
        view: 'ดู',
        preorder_exclusive: 'สั่งจองล่วงหน้าเท่านั้น',
        limited_edition: 'จำนวนจำกัด',
        in_stock_ready_ship: 'มีสต็อก - พร้อมจัดส่ง',
        immediate_delivery: 'จัดส่งทันที',
        preorder_price: 'ราคาสั่งจองล่วงหน้า',
        now: 'ตอนนี้',
        on_release: 'เมื่อวางจำหน่าย',
        regular_price: 'ราคาปกติ',
        ships_within_days: 'จัดส่งภายใน 2-3 วันทำการ',
        quantity: 'จำนวน',
        max_units: 'สูงสุด',
        units: 'ชิ้น',
        out_of_stock: 'หมดสต็อก',
        product_details: 'รายละเอียดสินค้า',
        stock: 'สต็อก',
        product_id_label: 'รหัสสินค้า',
        material_specifications: 'วัสดุและข้อมูลจำเพาะ',
        material: 'วัสดุ',
        premium_pvc_vinyl: 'พีวีซีไวนิลพรีเมียม',
        height: 'สูง',
        weight: 'น้ำหนัก',
        base: 'ฐาน',
        paint: 'การระบายสี',
        hand_painted_details: 'รายละเอียดที่ระบายด้วยมือ',
        packaging: 'บรรจุภัณฑ์',
        collectors_box: 'กล่องสะสม',
        authenticity: 'ความแท้',
        certificate_included: 'มีใบรับรอง',
        limited_edition_pieces: '500 ชิ้นทั่วโลก',
        // Profile keys
        profile_updated_successfully: 'อัปเดตโปรไฟล์สำเร็จแล้ว!',
        failed_to_update_profile: 'อัปเดตโปรไฟล์ล้มเหลว',
        session_expired_login_again: 'หมดอายุการใช้งาน กรุณาเข้าสู่ระบบใหม่',
        error_updating_profile: 'เกิดข้อผิดพลาดขณะอัปเดตโปรไฟล์',
        passwords_do_not_match: 'รหัสผ่านไม่ตรงกัน',
        cancel: 'ยกเลิก',
        edit_profile: 'แก้ไขโปรไฟล์',
        change_password: 'เปลี่ยนรหัสผ่าน',
        username_label: 'ชื่อผู้ใช้',
        full_name_label: 'ชื่อเต็ม',
        phone_label: 'เบอร์โทรศัพท์',
        social_media: 'โซเชียลมีเดีย',
        facebook_url: 'URL Facebook',
        facebook_url_placeholder: 'https://facebook.com/...',
        facebook_name_placeholder: 'ชื่อ Facebook',
        twitter_url: 'URL Twitter',
        twitter_url_placeholder: 'https://twitter.com/...',
        twitter_name_placeholder: 'ชื่อ Twitter',
        line_id_url: 'Line ID/URL',
        line_id_placeholder: 'Line ID',
        line_name_placeholder: 'ชื่อ Line',
        address: 'ที่อยู่',
        loading_address_data: 'กำลังโหลดข้อมูลที่อยู่...',
        house_number: 'บ้านเลขที่',
        house_number_placeholder: '123/45 หมู่บ้านที่ 1',
        province: 'จังหวัด',
        select_province: 'เลือกจังหวัด',
        district: 'อำเภอ',
        select_district: 'เลือกอำเภอ',
        sub_district: 'ตำบล',
        select_sub_district: 'เลือกตำบล',
        postal_code: 'รหัสไปรณีย์',
        auto_filled: 'กรอกอัตโนมัติ',
        saving: 'กำลังบันทึก...',
        save_changes: 'บันทึกการเปลี่ยนแปลง',
        new_password: 'รหัสผ่านใหม่',
        new_password_placeholder: 'รหัสผ่านใหม่',
        confirm_password_label: 'ยืนยันรหัสผ่าน',
        confirm_new_password_placeholder: 'ยืนยันรหัสผ่านใหม่',
        update_password: 'อัปเดตรหัสผ่าน',
        shipping_address: 'ที่อยู่จัดส่ง',
        no_orders_found: 'ไม่พบคำสั่งซื้อ',
        order: 'คำสั่งซื้อ',
        my_favorites: 'รายการโปรด',
        liked_products: 'สินค้าที่ถูกใจ',
        liked_fandoms: 'แฟนดอมที่ถูกใจ',
        no_favorite_products: 'ยังไม่มีสินค้าที่ถูกใจ',
        unlike: 'เลิกถูกใจ',
        no_favorite_fandoms: 'ยังไม่มีแฟนดอมที่ถูกใจ',
        delete_account: 'ลบบัญชี',
        delete_account_confirm_message: 'คุณแน่ใจจะลบบัญชีหรือไม่? การกระทำนี้ไม่สามารถยกเลิกได้และคุณจะสูญเสียข้อมูลทั้งหมด',
        delete: 'ลบ',
        // Updates additional keys
        by: 'โดย',
        grand_opening_title: 'เปิดตัวอย่างร้านค้าอออนไลน์ของ DomPort!',
        grand_opening_content: 'เรามีความปรีณีที่จะประกาศการเปิดตัวอย่างร้านค้าอออนไลน์ของ DomPort อย่างเป็นศูนย์ใจสำหรับอุปกรณ์อนิเมะและของสะสม! เพื่อเฉลิฉลองการเปิดตัว เรามอบแต้มพอยให้แก่องคะแนนสองลอนแรกครั้งแรกครั้งในสัปดาหนนี้',
        wonder_festival_title: 'สรุปปี Wonder Festival 2024',
        wonder_festival_content: 'Wonder Festival ฤดูหนาวเป็นไปได้อย่างมาก! เราได้เห็นตัวอย่างต่อไปของ Chainsaw Man และ Spy x Family ที่จะอออนมาในอนาคติว ตรวจสอรูปภาพจากจากพื้นพื้นของงาน',
        production_delay_title: 'ผลิตช้างเลื่อน: EVA Unit-01',
        production_delay_content: 'เราต้องขอออภัยว่าการวางจำหน่ายของ EVA Unit-01 Awakening statue ได้ถูกเลื่อนออกไป 2 เดือนเนื่องจากการปรับเปลี่ยนแปลงการผลิตเพื่อให้คุณภาพระดีสูงสุด เราขออภัยในความไม่สะดวสะดี',
        new_preorders_title: 'สั่งจองล่วงหน้าใหม่: Hololive Generation 3',
        new_preorders_content: 'เปิดรับสั่งจองล่วงหน้าสำหรับ Hololive Fantasy generation ทั้งหมด! จองตัวละครอบของ vtuber ที่คุณชื่นชอบในวันนี้ จำนวนจำกัด',
        // Updates additional features keys
        maintenance: 'Maintenance',
        product_launch: 'Launch',
        system_update: 'Update',
        search_updates_placeholder: 'Search updates...',
        sort_by: 'Sort by',
        sort_by_date: 'Date',
        sort_by_category: 'Category',
        reading_time: 'Reading time',
        minutes: 'minutes',
        update_statistics: 'Update Statistics',
        total_updates: 'Total Updates',
        announcements: 'Announcements',
        events: 'Events',
        // Updates page missing keys
        news_updates: 'ข่าวสารและอัปเดต',
        updates_description: 'อัปเดตข่าวสารล่าสุด ประกาศ และกิจกรรมจาก DomPort',
        all: 'ทั้งหมด',
        announcement: 'ประกาศ',
        new_release: 'วางจำหน่ายใหม่',
        event: 'กิจกรรม',
        delay: 'เลื่อน',
        no_updates_category: 'ไม่พบอัปเดตในหมวดหมู่นี้',
        // Footer
        shop: 'เลือกซื้อสินค้า',
        who_we_are: 'DomPort คือใคร?',
        support: 'ช่วยเหลือ',
        all_products: 'สินค้าทั้งหมด',
        vinyl_figures: 'หุ่นไวนิล',
        for_fandoms: 'สำหรับแฟนดอม',
        help_center: 'Help center',
        track_order: 'ติดตามคำสั่งซื้อ',

        // Login/Register
        welcome_back: 'ยินดีต้อนรับกลับมา',
        sign_in_desc: 'เข้าสู่ระบบเพื่อจัดการคอลเลกชันของคุณ',
        username: 'ชื่อผู้ใช้',
        password: 'รหัสผ่าน',
        email: 'อีเมล',
        confirm_password: 'ยืนยันรหัสผ่าน',
        remember_me: 'จำฉันไว้',
        sign_in: 'เข้าสู่ระบบ',
        signing_in: 'กำลังเข้าสู่ระบบ...',
        dont_have_account: "ยังไม่มีบัญชี?",
        sign_up: 'สมัครสมาชิก',
        create_account: 'สร้างบัญชีใหม่',
        join_us: 'เข้าร่วม DomPort วันนี้',
        creating_account: 'กำลังสร้างบัญชี...',
        already_have_account: 'มีบัญชีอยู่แล้ว?',
        login_here: 'เข้าสู่ระบบที่นี่',

        // Statuses
        status_delivered: 'จัดส่งแล้ว',
        status_shipped: 'กำลังจัดส่ง',
        status_pending: 'รอดำเนินการ',
        status_cancelled: 'ยกเลิก',

        // Profile specific
        order_history: 'ประวัติและการติดตามคำสั่งซื้อ',

        // PreOrder
        exclusive_preorders: 'พรีออเดอร์สุดพิเศษ',
        preorder_subtitle: 'จองไอเท็มที่ทุกคนรอคอยก่อนใคร',
        release_date: 'วางจำหน่าย',
        total_price: 'ราคาทั้งหมด',
        deposit: 'มัดจำ',
        preorder_now: 'จองเลย',

        // Catalog
        explore_fandoms: 'สำรวจโลกแฟนดอม',
        catalog_subtitle: 'ค้นหาสินค้าจากซีรีส์โปรดของคุณ',
        search_placeholder: 'ค้นหาสินค้า...',
        max_price: 'ราคาสูงสุด',
        no_items_found: 'ไม่พบสินค้าที่ตรงกับเงื่อนไข',
        reset_filters: 'ล้างตัวกรอง',
        view_details: 'ดูรายละเอียด',
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>('th');

    useEffect(() => {
        const savedLang = localStorage.getItem('language') as Language;
        if (savedLang && (savedLang === 'en' || savedLang === 'th')) {
            setLanguageState(savedLang);
        } else {
            // Set default to Thai if no saved language
            setLanguageState('th');
            localStorage.setItem('language', 'th');
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
